spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-provider
server:
  port: 8082
#  注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      会自动将数据库返回的列下划线去转成驼峰再进行set
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#    控制台打印sql语句
logging:
  level:
    com.lz.springcloud.usereurekaclient.dao: DEBUG
#    配置spring boot  actuator
#    1.在pom文件中加入spring boot actuator的依赖 就可以访问了
#    2.由于spring boot 2.x 为了安全只开放了/health 和/ info（自己配置了一些客户端可以看见的信息）
#    3.开发所有端点：management.endpoints.web.exposure.include=*(也可开放指定端点)
#    4.访问路径为/ip:port/actuator/...
info.app.name: spring-cloud-actuator
info:
  app:
    encoding: UTF-8
    java: 1.8.0_181
info.app.target: 1.8.0_181