
server:
  port: 8092
spring:
  application:
    name: config-client
#    开启消息追溯/跟踪
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host:
    port:
    username:
    password:

#spring boot 2.x 为了安全默认只开放了info 和 health 其他端点需要手动开启
#spring boot 1.5 之后是提供了 关闭 安全的属性，但是 2.x里面已经过时了 management.security.enabled=false
management:
  endpoints:
    web:
      exposure:
        include: refresh
